# exposure-deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: exposure-deployment
spec:
  selector:
    matchLabels:
      app: exposure-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: exposure-deployment
    spec:
      containers:
        - name: exposure
          image: yizong/rtl:exposure_usd
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 10m
              memory: 80Mi
            requests:
              cpu: 10m
              memory: 80Mi
          ports:
            - containerPort: 8080
              name: "http-server"
      imagePullSecrets:
        - name: usd-docker-cred
---
apiVersion: v1
kind: Service
metadata:
  name: exposure
spec:
  ports:
    - name: client
      port: 8080
  selector:
    app: exposure-deployment
